site_name: giulia-pythontastic-toolkit
site_url: https://github.com/GiuliaGualtieri/giulia-pythontastic-toolkit
site_author: Giulia Gualtieri
site_description: A new Era of GPT has begun: Giulia's Pythontastic Toolkit is here for helping young python developers!

repo_name: GiuliaGualtieri/giulia-pythontastic-toolkit
repo_url: https://github.com/GiuliaGualtieri/giulia-pythontastic-toolkit

copyright: Copyright (c) 2022-present Giulia Gualtieri <giulia.gualtieri@mail.polimi.it>

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/giulia-pythontastic-toolkit/
    - icon: fontawesome/brands/github
      link: https://github.com/GiuliaGualtieri
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/REPLACE_TWITTER_USERNAME
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/REPLACE_LINKEDIN_USERNAME/

nav:
  - Home: index.md
  - License: license.md
